MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show, :new]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, except: [:index]
  resources :tracks, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :logged_in?

  def new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = ["How did you mess this up?"]
      render :new
    end

  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band
      @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = "at least put a letter"
      render :new
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def index
    @bands = Band.all
    render :index
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/views/bands/_band.html.erb
<br>
<%= link_to band.name, band_url(band) %>
<%= button_to "Edit", edit_band_url(band), method: :get %>
<%= button_to "Delete", band_url(band), method: :delete %>
<% band.albums.each do |album| %>
  <%= link_to album.title, album_url(album) %>
  <br>
<% end %>

MusicApp/app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

MusicApp/app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

MusicApp/app/views/bands/edit.html.erb
<h1>Edit this Band</h1>

<form action= "<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label for="name">Band Name</label>
  <input type="text" name="band[name]" value="<%= @band.name %>">
  <input type="submit">
</form>

MusicApp/app/views/bands/index.html.erb
<%= render @bands %>
<br>
<%= link_to "Add a band", new_band_url %>

MusicApp/app/views/bands/new.html.erb
<h1>Add Band</h1>

<form action= "<%= bands_url %>" method="POST">
  <%= auth_token %>
  <label for="name">Band Name</label>
  <input type="text" name="band[name]" placeholder="e.g. Metallica">
  <input type="submit">
</form>

MusicApp/app/views/bands/show.html.erb
<%= render @band %>
<br>
<%= link_to "Add an album", new_album_url %>
<br>
<%= link_to "Back to all bands", bands_url%>

MusicApp/app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>