MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show, :new]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, except: [:index]
  resources :tracks, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :email, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 3, allow_nil: true}
  validates :password_digest, presence: { message: "Password can't be blank"}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end



end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/users/new.html.erb
<h1>Sign-up</h1>

<form action= "<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]"
         placeholder="user@email.com">
  <label for="password">Password</label>
  <input id="password" type="password"
         name="user[password]"
         placeholder="password">
  <input type="submit" value="Submit">
</form>

MusicApp/app/views/users/show.html.erb
<% if @user %>
  <%= @user.email %>
<% else %>
  <p> There is no user here! </p>
<% end %>
<br>
<br>
<%= link_to "Go to Bands", bands_url %>