MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show, :new]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, except: [:index]
  resources :tracks, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  song       :string           not null
#  lyrics     :text             not null
#  regular    :boolean          default("true"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :album_id, :song, presence: true
  validates :regular, inclusion: {in: [true, false]}

  belongs_to :album
  has_one :band, through: :album, source: :band
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :logged_in?
  
  def new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def update
    @track = Track.find_by(id: params[:id])
    if @track
      @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = "at least put a letter"
      render :new
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    album = @track.album
    @track.destroy
    redirect_to album_url(album)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :song, :lyrics, :regular)
  end
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/views/tracks/_track.html.erb
Song Title:  <%= track.song %>
<br>
Album: <a href="<%= album_url(track.album) %>"><%= track.album.title %></a>
<br>
Band: <a href="<%= band_url(track.album.band) %>"><%= track.album.band.name %></a>
 <p>Lyrics: <br> <%= track.lyrics %> </p>
Bonus?: <%= track.regular ? "no" : "yes"  %>

<%= button_to "Edit", edit_track_url(track), method: :get %>
<%= button_to "Delete", track_url(track), method: :delete %>

MusicApp/app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

MusicApp/app/views/tracks/edit.html.erb
<h1>Edit a Track</h1>

<form action= "<%= track_url %>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label for="name">Song Title</label>
  <input type="text" name="track[song]" value="<%= @track.song %>">
  <br>
  <label for="album_list">Choose an album</label>
  <select id="album_list" name="track[album_id]">
    <% Album.all.each do |album| %>
      <option <%= "selected" if @track.album == album %> value="<%= album.id %>"> <%= album.title %> </option>
    <% end %>
  </select>
  <br>
  <label>Bonus Track?: <br>
  <label for="false">Yes</label>
    <input <%= "checked" if @track.regular == false %> id="false" type="radio" value="false" name="track[regular]" >
  <label for="true">No</label>
    <input <%= "checked" if @track.regular == true %> id="true" type="radio" value="true" name="track[regular]">
  </label>
  <br>
  <label for="lyrics">Lyrics:
  </label>
  <br>
  <textarea id="lyrics" name= "track[lyrics]"><%= @track.lyrics %></textarea>

  <input type="submit">
</form>

MusicApp/app/views/tracks/new.html.erb
<h1>Add a Track</h1>

<form action= "<%= tracks_url %>" method="POST">
  <%= auth_token %>
  <label for="name">Song Title</label>
  <input type="text" name="track[song]" placeholder="e.g. Jumper">
  <br>
  <label for="album_list">Choose an album</label>
  <select id="album_list" name="track[album_id]">
    <option disabled selected>--Tracks--</option>
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"> <%= album.title %> </option>
    <% end %>
  </select>
  <br>
  <label>Bonus Track?: <br>
  <label for="false">Yes</label>
    <input id="false" type="radio" value="false" name="track[regular]">
  <label for="true">No</label>
    <input id="true" type="radio" value="true" name="track[regular]">
  </label>
  <br>
  <label for="lyrics">Lyrics:
  </label>
  <br>
  <textarea id="lyrics" name= "track[lyrics]"></textarea>

  <input type="submit">
</form>

MusicApp/app/views/tracks/show.html.erb
<%= render @track %>

MusicApp/app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>