MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show, :new]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, except: [:index]
  resources :tracks, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  live       :boolean          default("false"), not null
#

class Album < ApplicationRecord
  validates :band_id, :title, presence: true
  validates :live, inclusion: {in: [ true, false ] }

  has_many :tracks, dependent: :destroy
  belongs_to :band
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :logged_in?

  def new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album
      @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = "at least put a letter"
      render :new
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    band = @album.band
    @album.destroy
    redirect_to band_url(band)
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :title, :live)
  end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/views/albums/_album.html.erb
Album Title:  <%= album.title %>
<br>
Band: <a href="<%= band_url(album.band) %>"><%= album.band.name %></a>

<%= button_to "Edit", edit_album_url(album), method: :get %>
<%= button_to "Delete", album_url(album), method: :delete %>
<% album.tracks.each do |track| %>
  <%= link_to track.song, track_url(track) %>
  <br>
<% end %>

MusicApp/app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

MusicApp/app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

MusicApp/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<form action= "<%= album_url %>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label for="name">Title Name</label>
  <input type="text" name="album[title]" value="<%= @album.title %>">
  <br>
  <label for="band_list">Choose a band</label>
  <select id="band_list" name="album[band_id]">
    <% Band.all.each do |band| %>
      <option <%= "selected" if @album.band == band %> value="<%= band.id %>"> <%= band.name %> </option>
    <% end %>
  </select>
  <br>
  <label>Record Type: <br>
  <label for="true">Live</label>
    <input <%= "checked" if @album.live == true %> id="true" type="radio" value="true" name="album[live]">
  <label for="false">Studio</label>
    <input <%= "checked" if @album.live == false %> id="false" type="radio" value="false" name="album[live]">
  </label>
  <br>
  <input type="submit">
</form>

MusicApp/app/views/albums/new.html.erb
<h1>Add Album</h1>

<form action= "<%= albums_url %>" method="POST">
  <%= auth_token %>
  <label for="name">Title Name</label>
  <input type="text" name="album[title]" placeholder="e.g. Dark Side of the Moon">
  <br>
  <label for="band_list">Choose a band</label>
  <select id="band_list" name="album[band_id]">
    <option disabled selected>--Bands--</option>
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"> <%= band.name %> </option>
    <% end %>
  </select>
  <br>
  <label>Record Type: <br>
  <label for="true">Live</label>
    <input id="true" type="radio" value="true" name="album[live]">
  <label for="false">Studio</label>
    <input id="false" type="radio" value="false" name="album[live]">
  </label>
  <br>
  <input type="submit">
</form>

MusicApp/app/views/albums/show.html.erb
<%= render @album %>

<%= link_to "Add a track", new_track_url %>

MusicApp/app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>